### ISSUE TITLE
serve zeebe-simple-monitor from a prefixed route

### ISSUE THREAD

**Issue by shawnsarwar** [camunda-community-hub/zeebe-simple-monitor#170]
For any non-local development we will often deploy application behind and API gateway, and we typically chose to serve individual apps from a route as opposed to a sub-domain. I.E. `dev.domain.org/{app-route}/`

In trying to fit `zeebe-simple-monitor` into this framework we found that most of the routes are hard coded to expect `/` as the base path. Changing the `server.context-path` and `spring.mvc.static-path-pattern` only partially addressed the issue.

**Comment by shawnsarwar** [comment]
I've opened a PR to address this with an optional route-prefix set in `server.context-path`
https://github.com/zeebe-io/zeebe-simple-monitor/pull/171

**Comment by saig0** [comment]
@shawnsarwar thank you for raising this up and contributing :rocket: 
I'll have a look soon.

**Comment by saig0** [comment]
This was done by #209 :rocket:
