### ISSUE TITLE
Zeebe v1 support?

### ISSUE THREAD

**Issue by danshapir** [camunda-community-hub/zeebe-simple-monitor#238]
I've tried to use simple-monitor against v1, but it seems the zb.client needs to be updated. Is this planned?
I would help if I knew any Java, haha.

**Comment by saig0** [comment]
Yes. It is planned after Zeebe `1.0.0` is released. 
We need to adjust some dependent libraries first.

**Comment by danshapir** [comment]
Awesome!

**Comment by danshapir** [comment]
V1 has been released :)

**Comment by EugeneIstomin** [comment]
Hello!
Zeebe-hazelcast-exporter is v1.0.0-ready now (https://github.com/camunda-community-hub/zeebe-hazelcast-exporter/releases/tag/1.0.0), can you please update simple monitor?

Thanks )

**Comment by saig0** [comment]
No pressure 😂 
I'll try to work on it tomorrow 🚀

**Comment by danshapir** [comment]
@saig0 there was no docker image pushed to docker-hub, so I can't use it

**Comment by saig0** [comment]
Yes. The docker image moved to GitHub packages. 

https://github.com/camunda-community-hub/zeebe-simple-monitor/pull/250#issuecomment-850865438
