### ISSUE TITLE
Create a docker image with postgres 

### ISSUE THREAD

**Issue by danshapir** [camunda-community-hub/zeebe-simple-monitor#254]
Hey,

When you want to use this awesome project with k8s and need PostgreSQL, it's extremely hard to achieve without a prebuilt docker image that already contains the PostgreSQL driver preconfigured.

Can you please add to your release? 

Thanks,
Dan

**Comment by saig0** [comment]
Yes! The easiest option would be to include the Postgres driver directly. For example, like it was done recently for ZeeQS: camunda-community-hub/zeeqs#163

**Comment by saig0** [comment]
Done by #307 :tada:
