### ISSUE TITLE
Unable to view the deployed processes

### ISSUE THREAD

**Issue by SiddarthSingh** [camunda-community-hub/zeebe-simple-monitor#257]
Steps to reproduce:
1.  Deploy a process using simple monitor new deployment.
2.  Click on refresh notification.

Component used:
1. zeebe version 1.0.0.
2. zeebe hazelcast exporter version 1.0.0 with default configuration.
3. hazelcast version 4.1.2.
3. simple-monitor version 2.0.1-SNAPSHOT/Latest

*Note : Able to see all created process-instance in simple-monitor which were created using zeebe cli.

**Comment by SiddarthSingh** [comment]
resolved!!!

**Comment by saig0** [comment]
I'm happy to hear that the issue is solved.

Do you know what was the problem? I could help others to know more about it.

**Comment by SiddarthSingh** [comment]
@saig0  It is strange, but after deploying http-worker, the issue was resolved and I was able to see the processes as well.
Not sure how simple-monitor is related to http-worker.

**Comment by saig0** [comment]
That's weird :smile: 

Please reopen the issue if you're facing the behavior again.
