### ISSUE TITLE
Sorting - everything is sorted ASC and not DESC

### ISSUE THREAD

**Issue by danshapir** [camunda-community-hub/zeebe-simple-monitor#275]
The normal flow of interacting with the monitor is to monitor the latest jobs, instances, workflows, and so on, but everything is ordered ASC and not DESC (and there isn't any sorting ability).

How can one have the tables sorted DESC and not ASC? If you could direct me to the code I don't mind doing a pull request (not a java developer, but...).

Thanks!

**Comment by saig0** [comment]
Adding the ability to sort every table and column would be a bigger change.

Which tables are the most important for you?
By which column do you want to sort?

**Comment by danshapir** [comment]
@saig0 processes (main page) 
And under each process the instances table (once you enter a process, you see his instances) 

Sorting by date

Many many thanks!

**Comment by saig0** [comment]
Okay, I'll try to implement something for these tables (in the next weeks). Hopefully, this pattern can be applied later for other tables as well :rocket:

**Comment by saig0** [comment]
Idea:
* use the [Spring Data Web support](https://www.baeldung.com/spring-data-web-support)
* sort the processes by adding `?sort=timestamp,desc`
* sort the instances by adding `sort=start,desc`
* add the deployment time to the processes table
* have a button (or link) to change the ordering
* configure the default ordering in the app config
