### ISSUE TITLE
Bug: Variables and ElementInstances not stored in DB -- bug-fix proposal & guidance needed

### ISSUE THREAD

**Issue by nitram509** [camunda-community-hub/zeebe-simple-monitor#278]
## Problem / Bug (abstract)

Sometimes, process instances and variables are not visible in Simple Monitor by either being not present at all (in DB) or even result in HTTP 500 issues (deferred error).

## Request

I already found the root cause and being able to create a PR, 
but need some guidance on how to make the bug-fix "correct".

## Problem details

* I'm running Simple Monitor (latest) with a 3-node Zeebe Cluster (latest) setup and Hazelcast Exporter.
* I did deploy a simple "hello world" workflow successfully.
* I did create 2 instances via CLI tool sequentially within a single second
* ==> as a result, two instances are visible in Simple Monitor instances list view, but when I click on the details of the second one, the Simple Monitor crashes with HTTP 500.

Stacktrace (please, be aware this is the original Stacktrace, but only showing the deferred problem. The root cause is somewhat different, see details below).

```json
{
    "timestamp": "2021-08-03T11:38:20.158+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "trace": "com.samskivert.mustache.MustacheException$Context: Resolved '.' to null (which is disallowed), on line 78\n\tat com.samskivert.mustache.Mustache$VariableSegment.execute(Mustache.java:877)\n\tat com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:920)\n\tat com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:941)\n\tat com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:920)\n\tat com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:956)\n\tat com.samskivert.mustache.Template.executeSegs(Template.java:170)\n\tat com.samskivert.mustache.Mustache$IncludedTemplateSegment.execute(Mustache.java:831)\n\tat com.samskivert.mustache.Template.executeSegs(Template.java:170)\n\tat com.samskivert.mustache.Template.execute(Template.java:137)\n\tat org.springframework.boot.web.servlet.view.MustacheView.renderMergedTemplateModel(MustacheView.java:80)\n\tat org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:179)\n\tat org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316)\n\tat org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1397)\n\tat org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1142)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)\n\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:655)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:764)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)\n\tat org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)\n\tat org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n",
    "message": "Resolved '.' to null (which is disallowed), on line 78",
    "path": "/views/instances/6755399441055752"
}
```

## Root cause

The issue originates from an implemented check for duplicates,
see https://github.com/camunda-community-hub/zeebe-simple-monitor/blob/fe2c166ee910547a2f8690e9e5d6dd5aac40945f/src/main/java/io/zeebe/monitor/zeebe/ZeebeImportService.java#L213
Also, the same code/check is implemented to check for duplicates in variables,
see https://github.com/camunda-community-hub/zeebe-simple-monitor/blob/fe2c166ee910547a2f8690e9e5d6dd5aac40945f/src/main/java/io/zeebe/monitor/zeebe/ZeebeImportService.java#L406

Because the events from Zeebe Exporter actually use a combined ```RecordKey``` with ```position``` and ```partitionId```,
the duplicate check by just position is wrong and leads to some events are filtered out by Simple Monitor and hence not stored in DB. 
See https://github.com/camunda-community-hub/zeebe-exporter-protobuf/blob/093e7314fcc276d42d080ddbdb445185adaa441a/src/main/proto/schema.proto#L14

I was able to log events on console STDOUT and could verify two events with equal ```position``` but different ```partitionId``` are received via Hazelcast and then filtered out by the duplicate-check code fragments.
This is IMHO one more proof, that all events should be stored in DB.

## Fix proposal(s)

Looking at the code, I have at least two proposals on how to fix the issue, but have to admit I don't know the Zeebe internals well enough, to judge on the better choice ... so I do appreciate your guidance.

In order to get the implementation correct, I would like to ask these questions:
* What is the scope of RecordId of a Exporter Event?
   * Is this globally unique? --> I guess no, since position in a ring-buffer can repeat itself.
   * Can this safely be re-use as Unique Identifier in another system? --> I guess no.
* Is there a need/requirement to check for duplicate entities in Simple Monitor?

### Variant A - drop the duplicate check for instance elements and variables

**Abstract:** this is the minimal invasive fix to solve the bug/problem.

**Approach**
For the two places (see above), I would delete this guarding code 
```java
if (!_____Repository.existsById(position)) {
```

### Variant B - drop duplicate checks and clean-up ID fields for all entities

**Abstract:** This would be a consistent behaviour/strategy for all entities, which not only fixes the issue/bug but also would improve performance. There's a chance of this being a breaking change and people might lose data when upgrading 
from a prior version (to be validated).

Currently, there's a varying use of ```partitionId``` and ```position``` in each Entity class, which IMHO should be consistent since the meaning/origin is the RecordId from the ProtoBuf Scheme.

**Approach**
* As mentioned in variant A, the guarding if clauses will be dropped
* Additionally, all *Entity classes will be consistently refactored, like this
   * the ```@Id``` annotations on the ```position``` field is dropped
   * depending on the answer of the guidance questions above, either a ```@EmbeddedId``` (with position and partitionId) will be used **OR** an autogenerated ID will be used instead
   * ```@Index``` will be defined on each column, which is actually used. E.g. ```processDefinitionKey``` on the ElementInstance. This should speed up the lookup performance.

### Proposal

Even if I can't oversee yet if the change in Variant leads to breaking changes,
I do highly recommend making the use and implementation of ```position``` and ```partitionId``` consistent in all entity classes, in order to have a correct implementation.

**Comment by saig0** [comment]
@nitram509 good catch and a great analysis :+1:
I agree that the duplication check based on the positions is not correct. We need to take the partition id into account.

Regarding your questions:

> What is the scope of RecordId of a Exporter Event?

Currently, the `RecordId` from the Protobuf schema is not used.

> Is this globally unique? --> I guess no, since position in a ring-buffer can repeat itself.

The sequence in a Hazelcast ring-buffer should be stable. But only if the ring-buffer is not recreated (i.e. when using an in-memory Hazelcast instance). 

> Can this safely be re-use as Unique Identifier in another system? --> I guess no.

The only safe identifier is the combination of partition-id and position.

> Is there a need/requirement to check for duplicate entities in Simple Monitor?
 
Yes! In Zeebe, an exporter can receive the same record multiple times. Usually, this is caused by a leader change of a partition. The new leader may export records that are already passed to the exporter.

----

I suggest a different solution. 

* don't remove the duplicated checks because they're required to avoid duplicated entries
* introduce a new `@Id` column for both entities
  * type: string 
  * value: `partitionId + "-" + position`   
  * logically, it is a composite (i.e. embedded-id) but it's easier to use a string column
* use the new column to check for duplicates
* changing the column is breaking change but I don't see a solution without changing the columns 

@nitram509 does this sounds good for you?

**Comment by nitram509** [comment]
Thank you @saig0 for your feedback, that answers my questions.
I will rework my PR towards that approach of a combined string as primary key.

One more question ... the other events do not check for duplicates ... should this check be better implemented for all event listeners?

**Comment by saig0** [comment]
> the other events do not check for duplicates ... should this check be better implemented for all event listeners?

For the other entities, the importer uses the record key to check for duplications. This is sufficient.
In the case of the variables and element instances, it's different because we want to track every occurrence (i.e. every variable update or state transition).

**Comment by nitram509** [comment]
@saig0 thank you for your explanation.
I realize, the use of the RecordId is not obvious. May I ask, if this is documented somewhere?

**Comment by saig0** [comment]
> I realize, the use of the RecordId is not obvious. May I ask, if this is documented somewhere?

The Camunda Cloud (Zeebe) documentation doesn't describe the uniqueness of records and the relation between the keys and positions very well. This part could be improved.

It is partially mentioned here:
* https://docs.camunda.io/docs/product-manuals/zeebe/technical-concepts/partitions#partition-data-layout
* https://docs.camunda.io/docs/product-manuals/zeebe/technical-concepts/process-lifecycles

**Comment by nitram509** [comment]
Thank you for your feedback.
As you suggested, I did split the prior PR into two ... #284 and #285

**Comment by nitram509** [comment]
@saig0 I know this is closed, but may I ask, if the partition ID value is a good selector for checking duplicates?
See https://github.com/camunda-community-hub/zeebe-simple-monitor/blob/400aefd266ce4edbeff25100fec57125d0776f88/src/main/java/io/zeebe/monitor/zeebe/importers/ProcessAndElementImporter.java#L33

Background: I'm facing issues, where deployed processes are not visible in the simple monitor. With no error in the logs I have a strong hypothesis, this check is not correct, no?
