### ISSUE TITLE
Class not found for postgres driver

### ISSUE THREAD

**Issue by bkomac** [camunda-community-hub/zeebe-simple-monitor#298]
With simple monitor docker image version ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.1.0 is not enough to mount postgres driver with a volume like this
```
volumes:
      - ./lib/postgresql-42.2.12.jar:/app/libs/postgresql-42.2.12.jar
```
Because the docker entrypoint is now like this:
`
java -cp @/app/jib-classpath-file io.zeebe.monitor.ZeebeSimpleMonitorApp
`
... and jar is never loaded.

Is there a way how to include postgresql-42.2.12.jar in the /app/jib-classpath-file?

**Comment by saig0** [comment]
I can confirm the behavior. It seems that Jib changed the behavior and doesn't load any JAR from the `libs` folder anymore. 

![Screenshot from 2021-09-21 09-16-26](https://user-images.githubusercontent.com/4305769/134127880-933c606a-ed00-4b5a-8bc2-c6815d0a81e6.png)

I think the easiest option would be to include the Postgres driver directly. For example, like it was done recently for ZeeQS: camunda-community-hub/zeeqs#163

**Comment by saig0** [comment]
Closing this issue in favor of #254.
