### ISSUE TITLE
Postgres driver missing - v2.1.0

### ISSUE THREAD

**Issue by danshapir** [camunda-community-hub/zeebe-simple-monitor#299]
java.lang.IllegalStateException: Cannot load driver class: org.postgresql.Driver

Updated to 2.1.0 from 2.0.0, same code, same everything, downloading into the volume the postgress jdbc jar file and that's the error I'm getting.
Has anything changed that might cause this from v2.0.0?

**Comment by danshapir** [comment]
@saig0 so I'm unsure as how to handle this issue currently.

**Comment by saig0** [comment]
I don't know how to use Postgres with version `2.1.0`. It could be not possible.

The easiest solution would be to implement #254 and release a new version.
