### ISSUE TITLE
New Deployment functionality stopped working since the upgrade to zeebe 1.2.1

### ISSUE THREAD

**Issue by mrsateeshp** [camunda-community-hub/zeebe-simple-monitor#308]
zeebe(zeebe-gateway-protocol-impl) 1.2.1 needs 3.18.0 version of com.google.protobuf:protobuf-java but zeebe-hazelcast-connector is brining in 3.15.6 which leads to runtime error when trying to use "New Deployment" functionality(error about GeneratedMessageV3.isStringEmpty method is not found). 

i temporarily excluded protobuf-java from  zeebe-hazelcast-connector locally to make simple monitor work:
         <dependency>
                <groupId>io.zeebe.hazelcast</groupId>
                <artifactId>zeebe-hazelcast-connector</artifactId>
                <version>${hazelcast.exporter.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.google.protobuf</groupId>
                        <artifactId>protobuf-java</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

**Comment by saig0** [comment]
@Benjoyo no. This is probably not releated.

There can be different reasons why the process is not imported. For example, the process was deployed before the simple monitor started, or the process record was not available in Hazelcast anymore (i.e. removed because of TTL or reaching the capacity of the ringbuffer).

**Comment by saig0** [comment]
I can't reproduce the issue anymore with version 2.4.0`. I assume that it is fixed (by dumping the dependencies). :heavy_check_mark: 

Please reopen the issue if you are facing the problem again in a recent version.
