### ISSUE TITLE
Fail to read from ring-buffer at sequence '1120738'

### ISSUE THREAD

**Issue by bugbugmaker** [camunda-community-hub/zeebe-simple-monitor#324]
@bugbugmaker the provided failure message is expected. It indicates that Zeebe exports the records faster to the ring-buffer as they are read (e.g. by the simple monitor).

What is your concrete question?

_Originally posted by @saig0 in https://github.com/camunda-community-hub/zeebe-hazelcast-exporter/issues/140#issuecomment-975165246_

**Comment by saig0** [comment]
Duplicate. Closing this issue in favor of https://github.com/camunda-community-hub/zeebe-hazelcast-exporter/issues/140
