### ISSUE TITLE
Import only 7 of 15 exported process instances

### ISSUE THREAD

**Issue by bugbugmaker** [camunda-community-hub/zeebe-simple-monitor#325]
When Zeebe processes are submitted concurrently, 15 processes are submitted, but Zeebe simple monitor only records seven process records, but 15 processes are successful. The background log consistently prints this warning log. What's the problem?

**Comment by saig0** [comment]
Duplicate. Closing this issue in favor of camunda-community-hub/zeebe-hazelcast-exporter#140
