### ISSUE TITLE
Pagination on Variables, Audit log, etc

### ISSUE THREAD

**Issue by AlexeiBaranov** [camunda-community-hub/zeebe-simple-monitor#328]
Is it possible to add pagination to Instance view tabs? I have long-running process which monitors folder for incoming files and submits new processes. It creates thousands of variable instances, and when I open the Instances view, it takes a long time to load and show all variables on single tab. Same issue with Audit log, Jobs and other tabs.

**Comment by saig0** [comment]
The idea sounds reasonable :+1: 

I'm happy to receive contributions. Probably, I don't have much time to build it myself :sweat_smile:

**Comment by AlexeiBaranov** [comment]
Unfortunately, I do not have enough Java experience to accomplish this task. Perhaps some kind of developer guide could help, but there is no such document in the project. I'm just starting to take my first steps with Zeebe and Simple Monitor. Have to say that I like it so far :)

**Comment by nitram509** [comment]
@AlexeiBaranov @saig0 
I think we can close this one since pagination was introduced with Release v2.3.0
https://github.com/camunda-community-hub/zeebe-simple-monitor/releases/tag/2.3.0
