### ISSUE TITLE
Support for Mysql connector

### ISSUE THREAD

**Issue by ojgutierrez** [camunda-community-hub/zeebe-simple-monitor#337]
Hi,

Until version 2.0.0 was posible to use Mysql DB for persistence, just adding config properties on compose or application.yaml, but in early releases we got this error message.

> Cannot load driver class: com.mysql.cj.jdbc.Driver

please can you add support for mysql db, including mysql connector dependency in pom

Thanks in advance.

Oswaldo

**Comment by ojgutierrez** [comment]
Hello, I think we should add mysql driver as a dependency, so it will be bundled into Docker image...
As you did on issue [#307](https://github.com/camunda-community-hub/zeebe-simple-monitor/pull/307)

**Comment by saig0** [comment]
@ojgutierrez  sounds good :+1: 

Feel free to contribute a pull request :rocket:
