### ISSUE TITLE
zeebe-simple-monitor database structure

### ISSUE THREAD

**Issue by huanhuansonggemao** [camunda-community-hub/zeebe-simple-monitor#372]
Dear,
       I am writing to ask for the database structure of zeebe-simple-monitor. Could you please give me the sql commands of creating all the tables in the database? I am working on transfer them to MySQL database. Thanks a lot for helping!
Best wishes,
Ge Yang

**Comment by saig0** [comment]
The SQL commands are generated by Spring. There is no handwritten SQL. Everything is based on Spring Data.

Supporting MySQL database should be easy. Just look at the configuration [here](https://github.com/camunda-community-hub/zeebe-simple-monitor#change-the-database). There is already another issue #337 open for supporting MySQL similar to PostgreSQL.
