### ISSUE TITLE
Navigation tab links on /views/instances/{key} page are broken when context-path is not /

### ISSUE THREAD

**Issue by befer** [camunda-community-hub/zeebe-simple-monitor#374]
The links defined for navigation tabs in the page template instance-detail-view.html don't include the {{context-path}}. 
When the monitor is configured to run on a URL path different from '/', these links will not work.

The fix should be quite simple, replace href="/views/... with href="{{context-path}}views/...

Version: `2.3.0`

**Comment by saig0** [comment]
@befer thank you for reporting :+1: 
I can confirm the issue. I'll fix it immediately.
