### ISSUE TITLE
Configuration of connection to Hazelcast cluster with custom name

### ISSUE THREAD

**Issue by dsalvet** [camunda-community-hub/zeebe-simple-monitor#385]
Hello,

I am trying to set up cluster with Zeebe broker, Hazelcast Exporter and Zeebe Simple Monitor. When I leave the cluster name to default "dev", everything works fine. But when I change the Hazelcast cluster name to anything but "dev", Zeebe Simple Monitor won't work as it can not connect to the cluster.

Could you please help me out how to configure the cluster name and possible credentials via environment variables as I run everything in Docker containers.

Thanks in advance

David

**Comment by saig0** [comment]
@dsalvet thank you for raising this up. Currently, the simple monitor doesn't allow configuring the Hazelcast cluster name. 

There was a PR before that could enable this feature: https://github.com/camunda-community-hub/zeebe-simple-monitor/pull/376. Feel free to contribute a similar PR for it :rocket:

**Comment by nitram509** [comment]
This feature meanwhile is implemented and released since https://github.com/camunda-community-hub/zeebe-simple-monitor/releases/tag/2.5.3-1

Search the current README for `clusterName`
