### ISSUE TITLE
Tasklist 810a3 doesn't start with simple monitor 2.3.0

### ISSUE THREAD

**Issue by asys3** [camunda-community-hub/zeebe-simple-monitor#427]
Hi,
with V810a3 I have problems with tasklist when adding simple monitor 2.3.0 (with hazelcast 1.2.1) to the default docker-compose file of Camunda plattform.
Everything works with plattform V8.0.3 but now there's an exception in tasklist's log preventing it from starting.
Any idea where's the problem?
I attached the modified docker-compose file as well the error log and the application.yml I use besides hazelcast 1.2.1 (jar with dependencies).

[zeebe-applicationSimple .yml.txt](https://github.com/camunda-community-hub/zeebe-simple-monitor/files/9179784/zeebe-applicationSimple.yml.txt)
[docker-compose-810a3Simple.yaml.txt](https://github.com/camunda-community-hub/zeebe-simple-monitor/files/9179794/docker-compose-810a3Simple.yaml.txt)
[tasklistErrorLog.txt](https://github.com/camunda-community-hub/zeebe-simple-monitor/files/9179811/tasklistErrorLog.txt)

Best regards,
Uwe

**Comment by saig0** [comment]
@asys3 thank you for reporting. But it seems to be an issue in Camunda Tasklist. Look at the following error:

```
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'camunda.tasklist.identity.issuerUrl' in value "${camunda.tasklist.identity.issuerUrl}"
```

Try with the lastest version `8.1.0-alpha4`.

I'm closing this issue because it is not related to the Zeebe simple monitor.
