### ISSUE TITLE
Prometheus instrumentation

### ISSUE THREAD

**Issue by darox** [camunda-community-hub/zeebe-simple-monitor#433]
Hi

Is there any chance, that we can get Prometheus instrumentation in zeebe-simple-monitor?

Best regards

**Comment by saig0** [comment]
@darox please share what exactly you are looking for. And why?

**Comment by darox** [comment]
@saig0 Sure. We're using simple-monitor to dump data into Postgres and it would very practical if we could monitor this process with Prometheus. I can also think of monitoring the process of importing data from Hazelcast. See. https://tanzu.vmware.com/developer/guides/spring-prometheus/ for an implementation example.

**Comment by saig0** [comment]
@darox thank you for the details. Please list the concrete metrics that you would like to see.

Contributions as pull requests are welcome :grin:

**Comment by darox** [comment]
@saig0 Just opened a PR, though the CLA seems to be pending, no idea why.

**Comment by saig0** [comment]
@darox awesome :tada: I'll have a look at your PR in a few days :eyes:

**Comment by darox** [comment]
@saig0 Amazing. I might work on additional custom instrumentation, but for that I will raise a new PR.
