### ISSUE TITLE
RFE: in incident view, enable filtering by processId and time

### ISSUE THREAD

**Issue by nitram509** [camunda-community-hub/zeebe-simple-monitor#438]
## Motivation / Use Case

The "Incident view" shows all incidents. In order to speed up the search for specific incidents,
it would be helpful to provide (column-based) filters. 
Especially in scenarios with 300+ incidents, finding a single one is quite time consuming

## Feature description

* in the UI it's possible to define a process ID (string) to just view incidents by this one
   * the string is meant to be a partial match for the processID
   * not case sensitive 
* in the UI it's possible to define a "from time" and a "to time" time window
   * both timestamps do define a time window, in which the incident did occur
   * the UI could provide convenient DateTime pickers for the user
* Optional: some convenient buttons exist, which speed up setting a time filter, like e.g. "last 7 days" or "last 24h".

It could be implemented within the column headers - as known from Excel.
OR
It could be implemented with dedicated form fields, on top of the incident table.

@saig0 What's your view?
PS: I'm willing to contribute, as usual ;)

**Comment by saig0** [comment]
@nitram509 sounds good to me :+1: I would keep it simple for the first try.

Looking forward to see your contribution :rocket:
