### ISSUE TITLE
RFE: enable sorting by state in process instance view

### ISSUE THREAD

**Issue by nitram509** [camunda-community-hub/zeebe-simple-monitor#440]
## Motivation / Use Case

In order to speed up the finding/search of active instances, it would be helpful to sort by state.

# Feature description

* in the process view, the table of the instances contains a sort button next to the column "state"
   * the sort button switches the sort order for the 'state' column (similar as now implemented for time)
* Optional: sorting preference of the user ist store in the local storage of the browser, for the user's convinience

@saig0 What's your view?
PS: I'm willing to contribute, as usual ;)

**Comment by saig0** [comment]
@nitram509 sounds good to me :+1: 

Looking forward to see your contribution :rocket:
