### ISSUE TITLE
K8S Setup

### ISSUE THREAD

**Issue by schmetzyannick** [camunda-community-hub/zeebe-simple-monitor#476]
Hello,

I am trying to setup zeebe-simple-monitor in k8s. 
The first problem I hab was CORS. Because the origin header is set to the Ingress FQDN, the ws upgarde is rejected. I already build the service with the ingress as allowed origin, which makes the upgarde working.

Now I am running into the next Problem. When I try to upload a new deployment, I am getting the success message. After a refresh nothing is there. Not sure where the problem is here, I will investigate this further next week, but it is quiet wierd that i am getting a response code 200 evene if the deploy was not successfuel. 

I think it could also be some cors stuff because if i use kubectl port-forword and access the pod directly, everything works fine. 

Also for future references it would be greate to haven an example yaml file for k8s with:
  - deployment
  - cluster ip
  - ingress

**Comment by schmetzyannick** [comment]
After further investigantion, the deployment problem only occures, if you have multiple gateways (see camunda helm chart) in front of the zeebe engine.

**Comment by nitram509** [comment]
PR #477 merged.
