### ISSUE TITLE
ZeebeSimpleMonitorApp start with error

### ISSUE THREAD

**Issue by hudishaun** [camunda-community-hub/zeebe-simple-monitor#541]
Hi~ 

I just did a build with the latest source code by maven command: mvn clean install. The building process is fine but when I started the Springboot application (io.zeebe.monitor.ZeebeSimpleMonitorApp), I got the following errors.

![image](https://user-images.githubusercontent.com/7734997/235167250-60f68945-3465-4b4a-9c4d-10f60e244801.png)

I tried rolling back the code and found that the errors occur after the below merge pull request (update zeebe-bom from 8.1.9 to 8.2.0). When I checkout code before this, everything is OK. 

<img width="679" alt="1682690470371" src="https://user-images.githubusercontent.com/7734997/235168776-fc3a2345-faee-4a91-aa90-381b960d376b.png">

Any suggestions? Thanks a lot!

Environment and Configuration:

- OpenJDK 17+
- Zeebe Broker : 8.3.0-SNAPSHOT with the latest code. Building from source code and start with standalone mode.
- Exporter: zeebe-hazelcast-exporter-1.4.1-SNAPSHOT-jar-with-dependencies
- application.yaml: default

**Comment by jaakkoraut** [comment]
I am facing the same issue. What version of Maven are you using? I could circumvent the issue by reverting back to Maven 3.8.8 from 3.9.

**Comment by hudishaun** [comment]
> circumvent

My Maven version is 3.8.6.

**Comment by hudishaun** [comment]
> I am facing the same issue. What version of Maven are you using? I could circumvent the issue by reverting back to Maven 3.8.8 from 3.9.

My Maven version is 3.8.6.

**Comment by jaakkoraut** [comment]
> > I am facing the same issue. What version of Maven are you using? I could circumvent the issue by reverting back to Maven 3.8.8 from 3.9.
> 
> My Maven version is 3.8.6.

Looks like I still get this error when I start up the application. But the Maven downgrade got rid of the unit test execution getting stuck and printing a similar error.

**Comment by jaakkoraut** [comment]
@hudishaun I believe this issue still persists as there has been no approval to the Zeebe Hazelcast Connector bump PR that fixes this issue.
