### ISSUE TITLE
[Question] Optional Kafka importer

### ISSUE THREAD

**Issue by gasymovrv** [camunda-community-hub/zeebe-simple-monitor#571]
Hello! 
We are going to use zeebe-simple-monitor in our production, but we need Kafka as Zeebe core exporter.
We have already analyzed your code and realized that we can implement a new optional Kafka importer.

@saig0 Is it possible to make such a contribution?

Thanks

**Comment by nvavilov** [comment]
Sounds great, i would definitely vote for this feature!

**Comment by saig0** [comment]
@gasymovrv sounds like a great idea. :+1: I would be open to other data sources. 

However, @nitram509 is currently the main contributor to this project. 

So, @nitram509 what do you think about it?

**Comment by nitram509** [comment]
I'm happy to support, review, and merge PRs - but I don't have time to work on this new feature.

**Comment by gasymovrv** [comment]
@nitram509 
Thank you! I'll start working on this feature taking into account all your comments

**Comment by nitram509** [comment]
Released via https://github.com/camunda-community-hub/zeebe-simple-monitor/releases/tag/2.6.0
