### ISSUE TITLE
When can we expect a next release?

### ISSUE THREAD

**Issue by slimequartz** [camunda-community-hub/zeebe-simple-monitor#576]
Current release 2.4.1 uses zeebe 8.0.6.
The main branch uses zeebe 8.2.x.
When can we expect a new release of zeebe simple monitor?
We would like to use zeebe 8.2 (coming from 8.1) in our product line. Can we expect problems using the current version of zeebe simple monitor 2.4.1 against a zeebe 8.2?

**Comment by nitram509** [comment]
@slimequartz thanks for your nudge, I will release a new version by today.
