### ISSUE TITLE
Cannot load driver class: com.mysql.jdbc.Driver

### ISSUE THREAD

**Issue by fwqaq** [camunda-community-hub/zeebe-simple-monitor#590]
I am using zeebe and zeebe simple monitor to push data to MySQL 5.6, and the following error occurred。

config:
`version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: ghcr.io/camunda-community-hub/zeebe-with-hazelcast-exporter:8.0.5
    environment:
      - ZEEBE_LOG_LEVEL=info
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ../lib/zeebe-hazelcast-exporter-1.2.0.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter-1.2.0.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network
  monitor:
    container_name: zeebe_monitor
    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.4.0
    environment:
      - zeebe.client.broker.gateway-address=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    volumes:
      - ./simple-monitor-application.yaml:/application.yaml
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
    networks:
      - zeebe_network`

`spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: luban_test
      password: luban_test@shequ2021
      driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    generate-ddl: true
    repositories:
      enabled: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mustache:
    prefix: classpath:/templates/
    suffix: .html
    expose-request-attributes: true

  data:
    web:
      pageable:
        default-page-size: 10

server:
  port: 8082
  servlet:
    context-path:

logging:
  level:
    root: ERROR
    io.zeebe: INFO
    io.zeebe.monitor: DEBUG
    com.hazelcast: WARN`

<img width="1511" alt="image" src="https://github.com/camunda-community-hub/zeebe-simple-monitor/assets/45515058/51ac1928-a273-47ea-9228-c436955504e2">

**Comment by nitram509** [comment]
Hi @fwqaq 
the MySQL Driver was bundled with the release [v2.5.1](https://github.com/camunda-community-hub/zeebe-simple-monitor/releases/tag/2.5.1).
Looking at your config, you're using 2.4.0 == which seems to me the answer to your question.
Please upgrade to a recent version.

PS: if there's some more errors, please open a new issue.
