### ISSUE TITLE
Variables are not displayed correctly

### ISSUE THREAD

**Issue by jbiblio** [camunda-community-hub/zeebe-simple-monitor#642]
The "Variables" view of an instance shows all variables with a pager, and uses that `Pageable` to query the variables from the database.

By default, the UI limits the number of variables displayed to 20 (`/views/instances/.../variable-list?page=0&size=20`).

So the [repository](https://github.com/camunda-community-hub/zeebe-simple-monitor/blob/main/src/main/java/io/zeebe/monitor/repository/VariableRepository.java#L26) returns the first 20 items and displays them.

Then we update some variables.

*Problem*
From now on, the list becomes incomplete and may show outdated variable values.

Example:
First, with `pageSize = 20`:
![image](https://github.com/camunda-community-hub/zeebe-simple-monitor/assets/6216504/a63266b5-004f-4565-b6eb-fb8ee42ebe82)

Second, with `pageSize = 100`:
![image](https://github.com/camunda-community-hub/zeebe-simple-monitor/assets/6216504/153a5f77-74b9-4a09-b80f-40ae1b6368be)
Please observe the 2 newer values `24` and `25`.

The "Variables" table still displays the outdated `12`, BTW. This is caused by the [view code](https://github.com/camunda-community-hub/zeebe-simple-monitor/blob/3d6c2e1c0485de1eb95eef04e554f31f3e87927f/src/main/java/io/zeebe/monitor/rest/InstancesVariableListController.java#L70), which relies on the database sort order of the result set.

*Proposal*
a) Simply remove the `Pageable` from the `VariableRepository`.
b) Sort the result by timestamp and ID, ~descending~ ascending, to get a reliable sort order vie the ListController.

This would return all variables at once, but the alternative would be some sophisticated SQL that returns the latest `pageSize` items by considering their history, which sounds not feasible for this issue.

**Comment by nitram509** [comment]
Thanks for reporting this issue.

Pagination was introduced to optimize page load times.
I consider correctness is more important than fast page load and agree in removing pagination for variables.
