### ISSUE TITLE
NullPointerException "errorEventDefinition.getError().getErrorCode()"

### ISSUE THREAD

**Issue by ikarakayali** [camunda-community-hub/zeebe-simple-monitor#646]
In Camunda version 8.3, it is now possible to permit the Error Start Event's Error Reference to take on a null value.
When we leave it null, BPMN can be uploaded; however, Simple Monitor throws an error as mentioned below.

NullPointerException
Cannot invoke "io.camunda.zeebe.model.bpmn.instance.Error.getErrorCode()" because the return value of "io.camunda.zeebe.model.bpmn.instance.ErrorEventDefinition.getError()" is null

**Comment by nitram509** [comment]
Thanks for reporting this.
What version of Simple Monitor you use?

**Comment by ikarakayali** [comment]
You're welcome.
it is 2.6.1
