### ISSUE TITLE
Export metrics

### ISSUE THREAD

**Issue by jbiblio** [camunda-community-hub/zeebe-simple-monitor#708]
"As a operations engineer, I'd like to get insights into the import process by looking onto some metrics, to be able to debug issues, measure the amount of work that has been done etc."

I'd like to propose https://github.com/camunda-community-hub/zeebe-simple-monitor/pull/703.

This would expose some metrics about the import process and the Hazelcast connection.

**Comment by nitram509** [comment]
Merged, thank you for your contribution.
