### ISSUE TITLE
Search processes by process ID

### ISSUE THREAD

**Issue by jbiblio** [camunda-community-hub/zeebe-simple-monitor#709]
"As a BPMN maintainer, I'd like to be able to search processes by their ID."

I'd like to propsoe https://github.com/camunda-community-hub/zeebe-simple-monitor/pull/704.

This would introduce a simple search box by `BPMN process id`. The PR contains a rather simple implementation:
- minimum 3 characters (to not return all processes by an empty search)
- "starts with" semantics (search for `proce*`)
- add an additional index on some column.

That index may cause issues when deploying this feature on a large data set, since it may block the database completely (seen on Postgres).

--> A warning on the release page would be good.

**Comment by nitram509** [comment]
Merged, see #757

**Comment by nitram509** [comment]
Thank you for your contribution 🚀
