### ISSUE TITLE
Update GitHub Action for Maven Deployment

### ISSUE THREAD

**Issue by xomiamoore** [camunda-community-hub/zeebe-simple-monitor#725]
Hello! We had to make a few changes to our community's Maven deployment action. Specifically, we updated the secret names and deployment credentials.

Please update to [the latest release, v. 1.2.1](https://github.com/camunda-community-hub/community-action-maven-release/releases/tag/v1.2.1), to make sure your Action works. Thank you!

**Comment by nitram509** [comment]
Solved, see also #759
