### ISSUE TITLE
What are the plans for this project?

### ISSUE THREAD

**Issue by bespaltovyj** [camunda-community-hub/zeebe-simple-monitor#752]
Hello everyone, this project looks attractive.
Can you tell me if you plan its further development or what its future fate is?

**Comment by nitram509** [comment]
Hi, this is a community project. There's no long-term roadmap.
It lives from contributions of the community members. 
Contributions in any kind are welcome, from submitting issues and pull requests, to supporting others, which raise questions or adding documentation.

**Comment by bespaltovyj** [comment]
@nitram509 If I propose some changes and make them, will they be reviewed by someone?

I want to understand for myself whether it is necessary to spend effort on it.

**Comment by nitram509** [comment]
@bespaltovyj sure, will give my best to review.
Also, when there are major changed planned ... feel free to create an issue first and I'm glad to discuss solution ideas.
